spring:
  application:
    name: pocopentelemetry

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    driver-class-name: org.postgresql.Driver
    username: testuser
    password: secret

  #Sqlite is not supported out of the box
  data:
    jdbc:
      dialect: postgresql