spring:
  application:
    name: pocopentelemetry

  datasource:
    url: jdbc:sqlite:tools/db/init_db.db
    driver-class-name: org.sqlite.JDBC
    username: testuser
    password: testuser

  #Sqlite is not supported out of the box
  data:
    jdbc:
      dialect: h2