spring:
  application:
    name: pocopentelemetry

  datasource:
    url: jdbc:postgresql://raspberry1.local:5432/testdb
    username: testuser
    password: secret

  #Sqlite is not supported out of the box
  data:
    jdbc:
      dialect: postgresql