receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  jaeger:
    endpoint: "jaeger-service:14250"
    tls:
      insecure: true
  otlp/logs:
    endpoint: "localhost:4318"  # Or configure to another log endpoint if desired
    compression: "none"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
    logs:
      receivers: [otlp]
      exporters: [otlp/logs]  # Use OTLP for logs