version: '3.8'

services:
  dbmaria:
    image: mariadb:latest
    container_name: dbmaria
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser
    networks:
      - otel_default
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

networks:
  otel_default:
    driver: bridge

volumes:
  mariadb_data:

